CREATE TABLE IF NOT EXISTS Comments (
    id INTEGER PRIMARY KEY,
    text TEXT NOT NULL,
    authorId INTEGER NOT NULL,
    postId INTEGER NOT NULL,
    date TEXT NOT NULL,
    isDeleted INTEGER DEFAULT 0,
    FOREIGN KEY (postId) REFERENCES Posts (id) ON DELETE CASCADE,
    FOREIGN KEY (authorId) REFERENCES Users (id) ON DELETE RESTRICT
);